apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: cs3219
  labels:
    app: customer-service
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31308